### ISSUE TITLE
Internal Server Error - Med

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#1018] opened 2019-08-02 08:51 UTC
Clicking on Distribution Reports throws up error.

![image](https://user-images.githubusercontent.com/31128624/62357517-ea3b2580-b51b-11e9-8857-262d769dc6f9.png)

**Comment by bamoure** [comment] 2019-08-02 09:07
Duplicate of https://github.com/ReliefApplications/bms_front/issues/997

**Closed by bamoure** 2019-08-02 09:07 UTC
