### ISSUE TITLE
Offline Mode Not Working - Critical

### ISSUE THREAD

**Issue by Happs80** [ReliefApplications/bms_front#1010] opened 2019-07-25 14:48 UTC
Seems to be 'marking' as offline for all users.

![image](https://user-images.githubusercontent.com/31128624/61884181-0fb4a780-aefc-11e9-8399-d7793f9c7eda.png)

**Comment by bamoure** [comment] 2019-07-29 06:30
What do you mean?

**Comment by bamoure** [comment] 2019-07-29 06:32
Duplicate of #1008

**Closed by bamoure** 2019-07-29 06:32 UTC
Labels: Critical
